/* Auto-generated by scripts/generate-daos.ts.
 * Do NOT edit this file manually.
 */
import { BaseDao } from '../lib/base.dao.ts'
import { SchemaRegistry, type SchemaOf } from '../schemas/index.ts'

type Example = SchemaOf<'Example'>

export class ExampleDao extends BaseDao<Example> {
  constructor() {
    super(SchemaRegistry.Example)
  }
}
