/* Auto-generated by scripts/generate-daos.ts.
 * Do NOT edit this file manually.
 */
import { keys } from 'lodash-es'

import { ExampleDao } from './example.dao.ts'

import type { DaoConstructor } from '../lib/base.dao.ts'
import type {
  Example,
  SchemaName,
  SchemaOf,
} from '../schemas/index.ts'

export const DaoRegistry = {
  ExampleDao
} as const
export type DaoRegistry = typeof DaoRegistry
export type DaoName = keyof typeof DaoRegistry
export const DaoNames = keys(DaoRegistry) as DaoName[]
export type DaoEntityMap = {
  ExampleDao: Example
}

export type DaoConstructorMap = {
  ExampleDao: DaoConstructor<Example>
}
// Entity type of a given DAO name (e.g. 'UsersDao' -> Users)
export type EntityOfDao<D extends DaoName> = D extends `${infer M}Dao`
  ? SchemaOf<M & SchemaName>
  : never
// DAO class type of a given model name (e.g. DaoOf<'Users'> -> typeof UsersDao)
export type DaoOf<M extends SchemaName> = DaoRegistry[`${M}Dao`]
