/* Auto-generated by scripts/generate-schemas.ts.
 * Do NOT edit this file manually.
 */
import { z } from 'zod'

/** ActionTypes schema (table: dbo.action_types) */
export const ExampleSchema = z
  .object({
    id: z.number().int().meta({ sqlType: 'int' }),
    label: z.string().max(50).nullable().meta({ sqlType: 'nvarchar' }),
    created_at: z.iso.datetime().nullable().meta({ sqlType: 'datetime2' }),
    updated_at: z.iso.datetime().nullable().meta({ sqlType: 'datetime2' }),
  })
  .meta({
    primary: ['id'],
    unique: ['label'],
    foreignKey: [{ column: 'fk_id', table: 'fks', key: 'id' },],
    description: 'examples',
  })

export type Example = z.infer<typeof ExampleSchema>
