/* Auto-generated by scripts/generate-schemas.ts.
 * Do NOT edit this file manually.
 */
import { keys } from 'lodash-es'

import { ExampleSchema } from './example.schema.ts'

import type { z } from 'zod'

export type { Example } from './example.schema.ts'

export const SchemaRegistry = {
  Example: ExampleSchema,
} as const

export type SchemaRegistry = typeof SchemaRegistry
export type SchemaName = keyof SchemaRegistry
export type SchemaOf<N extends SchemaName> = z.infer<SchemaRegistry[N]>
export const SchemaNames = keys(SchemaRegistry) as SchemaName[]
